[GLOBAL]
pants_version = "2.26.0"

backend_packages = [
    "pants.backend.python",
    "pants.backend.python.lint.black",
    "pants.backend.python.lint.isort",
    "pants.backend.python.typecheck.mypy",
]

[anonymous-telemetry]
enabled = true
repo_id = "e0b99427-9bc2-4f6a-b197-f5f378849b15"

[mypy]
config = "tools/pyproject.toml"

[python]
enable_resolves = true
interpreter_constraints = [">=3.8,<3.15"]
pip_version = "24.3.1" # Matches the `pip-version` in tools_pex.rs
#separate_lockfile_metadata_file = true

# We generate this via cargo run -p package -- --update-lock.
resolves_generate_lockfiles = false

[python.resolves]
python-default = "tools/lock.json"

[python-infer]
use_rust_parser = true

[pex-cli]
version = "v2.91.2"
known_versions = [
    "v2.91.2|macos_arm64 |0aa2f9100c6775d7f6b1db1658d0c70a9f62d17e4cc7d1301df3e8fa364a1034|4992632",
    "v2.91.2|linux_x86_64|0aa2f9100c6775d7f6b1db1658d0c70a9f62d17e4cc7d1301df3e8fa364a1034|4992632",
    "v2.91.2|linux_arm64 |0aa2f9100c6775d7f6b1db1658d0c70a9f62d17e4cc7d1301df3e8fa364a1034|4992632",
]

[subprocess-environment]
env_vars = [
    "BUILDROOT=%(buildroot)s"
]

[source]
root_patterns = [
    "/tools",
    "/tools/src",
    "/tools/tests",
    "/tools/test_support",
]
