[GLOBAL]
pants_version = "2.26.0"

backend_packages = [
    "pants.backend.python",
    "pants.backend.python.lint.black",
    "pants.backend.python.lint.isort",
    "pants.backend.python.typecheck.mypy",
]

[anonymous-telemetry]
enabled = true
repo_id = "e0b99427-9bc2-4f6a-b197-f5f378849b15"

[mypy]
config = "tools/pyproject.toml"

[python]
enable_resolves = true
interpreter_constraints = [">=3.8,<3.15"]
pip_version = "24.3.1" # Matches the `pip-version` in tools_pex.rs
#separate_lockfile_metadata_file = true

# We generate this via cargo run -p package -- --update-lock.
resolves_generate_lockfiles = false

[python.resolves]
python-default = "tools/lock.json"

[python-infer]
use_rust_parser = true

[pex-cli]
version = "v2.92.3"
known_versions = [
    "v2.92.3|macos_arm64|925d08cc9ffe5cff5a3dd67519e24bdb42b1257814bcae7355bd594e33de139d|5082037",
    "v2.92.3|linux_x86_64|925d08cc9ffe5cff5a3dd67519e24bdb42b1257814bcae7355bd594e33de139d|5082037",
    "v2.92.3|linux_arm64|925d08cc9ffe5cff5a3dd67519e24bdb42b1257814bcae7355bd594e33de139d|5082037",
]

[subprocess-environment]
env_vars = [
    "BUILDROOT=%(buildroot)s"
]

[source]
root_patterns = [
    "/tools",
    "/tools/src",
    "/tools/tests",
    "/tools/test_support",
]
