# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

parameters:
  GHA_Actor:
    type: string
    default: ""
  GHA_Action:
    type: string
    default: ""
  GHA_Event:
    type: string
    default: ""
  GHA_Meta:
    type: string
    default: ""

orbs:
  gh: circleci/github-cli@2.1.1
  rust: circleci/rust@1.6.0

jobs:
  test:
    machine:
      image: ubuntu-2004:current
    resource_class: arm.medium
    environment:
      CARGO_TERM_COLOR: always
    steps:
      - checkout
      - rust/install:
          version: nightly
      - rust/format:
          nightly-toolchain: true
      - rust/install
      - rust/clippy
      - rust/test
  package:
    machine:
      image: ubuntu-2004:current
    resource_class: arm.medium
    environment:
      CARGO_TERM_COLOR: always
    steps:
      - checkout
      - rust/install
      - run:
          name: Package scie-pants
          command: |
            mkdir dist
            cargo run -p package -- --dest-dir dist/ tools
            docker run --rm \
              -v $PWD:/code \
              -w /code \
              rust:1.68.0-alpine3.17 \
                sh -c '
                  apk add cmake make musl-dev perl && \
                  cargo run -p package -- --dest-dir dist/ scie --tools-pex dist/tools.pex \
                '
      - persist_to_workspace:
          root: dist
          paths:
            - tools.pex
            - scie-pants*
  integration-test:
    machine:
      image: ubuntu-2004:current
    resource_class: arm.medium
    environment:
      CARGO_TERM_COLOR: always
    steps:
      - checkout
      - rust/install
      - attach_workspace:
          at: dist
      - run:
          name: Run integration tests
          command: |
            PANTS_BOOTSTRAP_GITHUB_API_BEARER_TOKEN=${GITHUB_TOKEN} \
              cargo run -p package -- test \
                --tools-pex dist/tools.pex --scie-pants dist/scie-pants-linux-aarch64 \
  release:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - gh/setup
      - attach_workspace:
          at: dist
      - run:
          name: Upload scie-pants-linux-aarch64 to << pipeline.parameters.GHA_Meta >> Github Release
          command: |
            gh release upload << pipeline.parameters.GHA_Meta >> dist/scie-pants* \
              --repo pantsbuild/scie-pants

workflows:
  ci:
    jobs:
      - test
      - package
      - integration-test:
          requires:
            - package
          context:
            - GITHUB_CREDS
  release:
    when: << pipeline.parameters.GHA_Action >>
    jobs:
      - test:
          filters:
            tags:
              only: /^v.*/
      - package:
          filters:
            tags:
              only: /^v.*/
      - release:
          filters:
            tags:
              only: /^v.*/
          requires:
            - test
            - package
          context:
            - GITHUB_CREDS

