[lift]
name = "pbt"
description = """\
Python Build Tool: A BusyBox that provides `python`, `pip`, `pex`, `pex3` and `pex-tools`.\
"""

[lift.ptex]
version = "1.7.0"

[lift.scie_jump]
version = "1.11.2"

[[lift.interpreters]]
id = "cpython"
provider = "PythonBuildStandalone"
release = "20241002"
lazy = true
version = "3.8.20"

[[lift.files]]
name = "pex"
type = "blob"
digest = { size = 5069818, fingerprint = "311d8eb35ad3d64e1c508b7e7ac3479e1fd40911117396f754a9914eb5faf017" }
source = { url = "https://github.com/pantsbuild/pex/releases/download/v2.90.2/pex", lazy = true }

[[lift.commands]]
name = "pex"
exe = "#{cpython:python}"
args = [
    "{pex}"
]

[[lift.commands]]
name = "pex3"
exe = "#{cpython:python}"
args = [
    "{pex}"
]

[lift.commands.env.replace]
PEX_SCRIPT = "pex3"

[[lift.commands]]
name = "pex-tools"
exe = "#{cpython:python}"
args = [
    "{pex}"
]

[lift.commands.env.replace]
PEX_SCRIPT = "pex-tools"

[[lift.commands]]
name = "pip"
exe = "#{cpython:python}"
args = [
    "-m",
    "pip"
]

[[lift.commands]]
name = "python"
exe = "#{cpython:python}"
