name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_call:
    outputs:
      artifact-name:
        description: The name of the uploaded artifacts
        value: ${{ jobs.ci.outputs.artifact-name }}
      artifact-path:
        description: The path of the uploaded artifacts
        value: ${{ jobs.ci.outputs.artifact-path }}

concurrency:
  group: CI-${{ github.ref }}
  # Queue on all branches and tags, but only cancel overlapping PR burns.
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' || !startsWith(github.ref, 'refs/tags/') }}

defaults:
  run:
    shell: bash

env:
  CARGO_TERM_COLOR: always

jobs:
  org-check:
    name: Check GitHub Organization
    if: github.repository_owner == 'pantsbuild'
    runs-on: ubuntu-22.04
    steps:
      - name: Noop
        run: "true"

  ci:
    name: (${{ matrix.name }}) CI
    needs: org-check
    runs-on: ${{ matrix.os }}
    env:
      PY: python3.11
      SCIE_PANTS_DEV_CACHE: .scie_pants_dev_cache
      SCIENCE_AUTH_API_GITHUB_COM_BEARER: ${{ secrets.GITHUB_TOKEN }}    
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-14
            name: macos-14-arm64
            target: aarch64-apple-darwin

          # - os: ubuntu-22.04
          #   name: ubuntu-22.04-x64-gnu
          #   target: x86_64-unknown-linux-gnu

          - os: ubuntu-22.04
            name: ubuntu-22.04-x64
            target: x86_64-unknown-linux-musl

          # - os: ubuntu-22.04-arm
          #   name: ubuntu-22.04-arm64-gnu
          #   target: aarch64-unknown-linux-gnu

          - os: ubuntu-22.04-arm
            name: ubuntu-22.04-arm64
            target: aarch64-unknown-linux-musl

          - os: windows-2022
            name: windows-2022-x64
            target: x86_64-pc-windows-msvc

    steps:
      - uses: actions/checkout@v6

      - name: Check Formatting
        run: |
          rustup toolchain add nightly -c rustfmt
          cargo +nightly fmt --check --all

      - name: Lint
        run: cargo clippy --locked --all

      - name: Unit Tests
        run: cargo test --all

      - name: Setup Python 3.9, 3.10, 3.11
        uses: actions/setup-python@v6
        with:
          python-version: |-
            3.9
            3.10
            3.11

      - name: Compute cache key
        id: build_it_cache_key
        run: |
          # The caches include venvs which have absolute links to Python binaries, so our system
          # should be resilient to this (see `test_pants_source_mode` in `test.rs`).
          echo "cache_key=${{ matrix.name }}-scie-pants-v7-$(which python)" | tee -a "$GITHUB_OUTPUT"

      - name: Cache Build and IT Artifacts
        uses: actions/cache@v5
        with:
          path: ${{ env.SCIE_PANTS_DEV_CACHE }}
          key: ${{ steps.build_it_cache_key.outputs.cache_key }}

      # required for the PANTS_SOURCE tests, which build a version of Pants that requires an external protoc
      - name: Install Protoc
        uses: arduino/setup-protoc@c65c819552d16ad3c9b72d9dfd5ba5237b9c906b # v3.0.0
        if: ${{ matrix.name != 'windows-2022-x64' }}
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          version: 23.x

      - name: Install platform target
        if: ${{ matrix.name != 'windows-2022-x64'}}
        env:
          TARGET: ${{ matrix.target }}
        run: |
          rustup target add $TARGET

      - name: Run Integration Tests
        if: ${{ matrix.name != 'windows-2022-x64'}}
        env:
          # Tests that scrape the github API may need this.
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TARGET: ${{ matrix.target }}
        run: |
          cargo run -p package -- --target $TARGET test \
            --check \
            --tools-pex-mismatch-warn

      - name: Package scie-pants ${{ matrix.name }} binary
        id: package
        if: ${{ matrix.name != 'windows-2022-x64' }}
        env:
          # So we can download PBS releases without hitting github API rate limits.
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NAME: ${{ matrix.name }}
          TARGET: ${{ matrix.target }}
        run: |
          cargo run -p package -- --dest-dir dist/ --target $TARGET scie

          echo "artifact-name=zipped-scie-pants-$NAME" >> "$GITHUB_OUTPUT"
          echo "artifact-path=dist/scie-pants-*" >> "$GITHUB_OUTPUT"

      - name: Upload artifacts
        if: ${{ matrix.name != 'windows-2022-x64' }}
        uses: actions/upload-artifact@v7
        with:
          name: ${{ steps.package.outputs.artifact-name }}
          path: ${{ steps.package.outputs.artifact-path }}
          retention-days: 3
