name: Release
on:
  workflow_dispatch:
    inputs:
      tag:
        description: The scie-pants release version (i.e. `v1.2.3`)
        required: true
      prerelease:
        description: |
          Is this a pre-release?
          These are not announced in Slack nor published to HomeBrew (i.e. `v1.2.3-beta.0`)
        type: boolean
        default: false
        required: true

defaults:
  run:
    shell: bash

env:
  CARGO_TERM_COLOR: always

jobs:
  org-check:
    name: Check GitHub Organization
    if: ${{ github.repository_owner == 'pantsbuild' }}
    runs-on: ubuntu-latest
    steps:
      - name: Noop
        run: "true"

  determine-tag:
    name: Determine the release tag to operate against.
    needs: org-check
    runs-on: ubuntu-latest
    env:
      RELEASE_TAG: ${{ github.event.inputs.tag }}
      PRERELEASE: ${{ github.event.inputs.prerelease }}
    outputs:
      release-tag: ${{ steps.determine-tag.outputs.release-tag }}
      release-version: ${{ steps.determine-tag.outputs.release-version }}
      prerelease: ${{ steps.determine-tag.outputs.prerelease }}

    steps:
      - name: Determine Tag
        id: determine-tag
        run: |
          if [[ "${RELEASE_TAG}" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]] || [[ "${PRERELEASE}" == true ]]; then
            echo "release-tag=${RELEASE_TAG}" >> $GITHUB_OUTPUT
            echo "release-version=${RELEASE_TAG#v}" >> $GITHUB_OUTPUT
            echo "prerelease=${PRERELEASE}" >> $GITHUB_OUTPUT
          else
            echo "::error::Release tag '${RELEASE_TAG}' must match 'v\d+.\d+.\d+' when not doing a pre-release."
            exit 1
          fi

  run-ci:
    needs: determine-tag
    uses: ./.github/workflows/ci.yml

  github-release:
    name: Create Github Release
    needs: 
      - determine-tag
      - run-ci
    runs-on: ubuntu-latest
    environment: Release
    permissions:
      id-token: write
      attestations: write
      contents: write
      discussions: write

    steps:
      - name: Sparse checkout (so 'gh' will work)
        uses: actions/checkout@v6
        with:
          sparse-checkout: |
            .

      - name: Download artifacts
        uses: actions/download-artifact@v8
        with:
          merge-multiple: true
          path: dist/

      - name: Create GitHub release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE_TAG: ${{ needs.determine-tag.outputs.release-tag }}
          RELEASE_VERSION: ${{ needs.determine-tag.outputs.release-version }}
          PRERELEASE: ${{ needs.determine-tag.outputs.prerelease }}
        run: |
          # Using Markdown headers, grab everything between the current version and subsequent (including current version title)
          CHANGELOG_NOTES=$(sed -n "/^## ${RELEASE_VERSION}/, /^## /p" CHANGES.md | sed '$d')

          PRERELEASE_FLAG=""
          if [[ "$PRERELEASE" != "false" ]]; then
            PRERELEASE_FLAG="--prerelease"
          fi

          gh release create \
            "$RELEASE_TAG" \
            dist/scie-pants-* \
            --discussion-category "Announcements" \
            --fail-on-no-commits \
            --notes "$CHANGELOG_NOTES" \
            --repo pantsbuild/scie-pants \
            --title "scie-pants $RELEASE_VERSION" \
            $PRERELEASE_FLAG

      - name: Generate ${{ needs.determine-tag.outputs.release-version }} build provenance attestations
        uses: actions/attest@v4
        with:
          subject-path: dist/scie-pants-*

  publish-announce-release:
    name: Publish and Announce Release
    needs:
      - determine-tag
      - github-release
    if: ${{ needs.determine-tag.outputs.prerelease != 'true' }}
    runs-on: ubuntu-latest

    steps:
      - name: Sparse checkout (to get the Changelog)
        uses: actions/checkout@v6
        with:
          sparse-checkout: |
            .

      - name: Post release announcement to Pants Slack in `#announce` channel
        uses: slackapi/slack-github-action@v3.0.1
        id: slack
        env:
          RELEASE_TAG: ${{ needs.determine-tag.outputs.release-tag }}
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        with:
          channel-id: "C18RRR4JK"
          # N.B.: You can muck with the JSON blob and see the results rendered here:
          #  https://app.slack.com/block-kit-builder
          payload: |
            {
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "The `pants` launcher binary (scie-pants) $RELEASE_TAG is released:\n* https://github.com/pantsbuild/scie-pants/releases/tag/${RELEASE_TAG}\n* https://www.pantsbuild.org/docs/installation"
                  }
                }
              ]
            }

  update-homebrew-tap:
    name: Update pantsbuild/homebrew-tap
    needs:
      - determine-tag
      - github-release
    if: ${{ needs.determine-tag.outputs.prerelease != 'true' }}
    runs-on: ubuntu-latest

    steps:
      - name: Bump `scie-pants` version in Casks/pants.rb to ${{ needs.determine-tag.outputs.release-tag }}
        env:
          GITHUB_TOKEN: ${{ secrets.TAP_TOKEN }}
          RELEASE_TAG: ${{ needs.determine-tag.outputs.release-tag }}
        run: |
          gh workflow run "release.yml" \
            --raw-field "tag=$RELEASE_TAG" \
            --repo pantsbuild/homebrew-tap
